name: Test
run-name: Tests for the experiment control software are being run
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Execute unit tests
      run: dotnet test GeneratorUT\GeneratorUT.csproj
