name: Test
run-name: Tests for the experiment control software are being run
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore packages
      run: msbuild MainProject\ExperimentControl.sln -t:restore

    - name: Build
      run: msbuild MainProject\ExperimentControl.sln -property:Configuration=Debug;Platform=x64 -t:build
      
    - name: Run tests
      uses: microsoft/vstest@v1.0.0
      with:
        testAssembly: GeneratorUT.dll
        searchFolder: .\GeneratorUT\bin\Debug\
